stages:
  - install
  - test
  - build
  - package

default:
  image: node:20-buster-slim

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - frontend/node_modules  # Cache the node_modules directory

unit-test:
  stage: test
  before_script:
    - cd frontend
    - ln -s $(pwd)/../frontend/node_modules ./node_modules  # Create a symlink to the cached node_modules
  script:
    - npm start

build-frontend:
  stage: build
  before_script:
    - cd frontend
    - ln -s $(pwd)/../frontend/node_modules ./node_modules  # Create a symlink to the cached node_modules
  script:
    - echo "building frontend application"
    - npm run build
