stages:
  - install
  - test
  - build
  - package

default:
  image: node:14

install_dependencies:
  stage: install
  script:
    - npm install

unit-test:
  stage: test
  before_script:
    - cd frontend
  script:
    - npm start

build-frontend:
  stage: build
  before_script:
    - cd frontend
  script:
    - echo "building frontend application"
    - npm run build
