stages:
  - install
  - test
  - build
  - security
  - build-image

default:
  image: node:20-buster-slim

install_dependencies:
  stage: install
  script:
    - npm install  # Install frontend project dependencies

unit-test:
  stage: test
  cache:
    key:
      files:
        - node.modules
    paths:
      - ..
  script:
    - npm install
    - echo "Running unit tests"

build-frontend:
  stage: build
  cache:
    key:
      files:
        - node.modules
    paths:
      - .
  script:
    - echo "Building frontend application"
    - cd frontend
    - npm install
    - npm run build

build-backend:
  stage: build
  cache:
    key:
      files:
        - node.modules
  script:
    - npm uninstall -g babel
    - npm install --save-dev babel-cli
    - npm install  # Install project dependencies
    - npx babel backend -d dist  # Run the build command directly

security_scan:
  stage: security
  include:
    - template: Jobs/SAST.gitlab-ci.yml

build-image_Frontend:
  stage: build-image
  cache:
    key:
      files:
        - node.modules
    paths:
      - frontend/
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cd frontend
    - apk add --no-cache git  # Install Git
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t elboukhariyoucef/my_stock_pro:mystockFrontend .
    - docker push elboukhariyoucef/my_stock_pro:mystockFrontend

build-image-backend:
  stage: build-image
  cache:
    key:
      files:
        - node.modules
    paths:
      - backend/
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cd backend
    - apk add --no-cache git  # Install Git
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t elboukhariyoucef/my_stock_pro:mystockBackend .
    - docker push elboukhariyoucef/my_stock_pro:mystockBackend
