stages:
  - install
  - test
  - Cache
  - build
  - security
  - build-image
  - scan

variables:
  SAST_IMAGE_SUFFIX: '-fips'

default:
  image: node:20-buster-slim

install_Dependencies:
  stage: install
  script:
    - npm install  # Install frontend project dependencies

.include:
  - template: Security/SAST.gitlab-ci.yml

.variables:
  SAST_EXCLUDED_ANALYZERS: "spotbugs"

.node-modules-Cache:
  stage: Cache
  script:
    - echo "This job uses a cache."
  cache:
    key: binaries-cache
    paths:
      - node_modules/

.build-frontend:
  stage: build
  cache:
    key:
      files:
        - node.modules
    paths:
      - .
  script:
    - echo "Building frontend application"
    - cd frontend
    - npm install
    - npm run build

.build-Backend:
  stage: build
  cache:
    key:
      files:
        - node.modules
  script:
    - npm uninstall -g babel
    - npm install --save-dev babel-cli
    - npm install  # Install project dependencies
    - npx babel backend -d dist  # Run the build command directly
    
build-image-Frontend:
  stage: build-image
  image: docker:24.0.6-dind
  services:
    - name: docker:24.0.6-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://localhost:2375  
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cd frontend
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - |
      docker run \
        --rm \
        --dns 8.8.8.8  # Replace with your preferred DNS server
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /certs/client:/certs/client \
        -e DOCKER_TLS_CERTDIR=/certs/client \
        -e DOCKER_HOST=tcp://docker:2376 \
        -e DOCKER_TLS_VERIFY=1 \
        -e DOCKER_CERT_PATH=/certs/client \
        -e DOCKER_API_VERSION=1.24 \
        "$REGISTRY_USER"/my_stock_pro:mystockFrontend
    - docker build -t "$REGISTRY_USER"/my_stock_pro:mystockFrontend .
    - docker push "$REGISTRY_USER"/my_stock_pro:mystockFrontend
  

.build-image-backend:
  stage: build-image
  cache:
    key:
      files:
        - node.modules
    paths:
      - backend/
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cd backend
    - apk add --no-cache git  # Install Git
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t elboukhariyoucef/my_stock_pro:mystockBackend .
    - docker push elboukhariyoucef/my_stock_pro:mystockBackend
scan_frontend_Image:
  stage: scan
  script:
    - echo "Running container scanning job for the frontend"
  variables:
    CS_IMAGE: elboukhariyoucef/my_stock_pro:mystockFrontend

.scan_backend_image:
  stage: scan
  script:
    - echo "Running container scanning job for the backtend"
  variables:
    CS_IMAGE: elboukhariyoucef/my_stock_pro:mystockBackend
