stages:
  - install
  - test
  - build

default:
  image: node:20-buster-slim

install_dependencies:
  stage: install
  script:
    - npm install

unit-test:
  stage: test
  script:
    - echo "unit test application"

integration-test:
  stage: test
  script:
    - echo "integration test application"

build-frontend:
  stage: build
  script:
    - echo "building frontend application"
    - cd frontend
    - npm install
    - npm run build
