stages:
  - install
  - test
  - build
  - build-image-docker

default:
  image: node:20-buster-slim

variables:
    - IMAGE_NAME : elboukhariyoucef/my_stock_pro
    - IMAGE_TAG : stock-pro-1.0

install_dependencies:
  stage: install
  script:
    - npm install

unit-test:
  stage: test
  script:
    - echo "unit test application"

integration-test:
  stage: test
  script:
    - echo "integration test application"

build-frontend:
  stage: build
  script:
    - echo "building frontend application"
    - cd frontend
    - npm install
    - npm run build
build-image :
  stage : build-image-docker
  image : docker:24.0.6
  services :
    - docker:24.0.6-dind
  variables :
    DOCKER_TLS_CERTDIR: "/certs"
  before_script :
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script :
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG .



