stages:
  - install
  - test
  - build
  - package

before_script :
  - cd frontend

default:
  image: node:14

.install_dependencies:
  stage: install
  script:
    - npm install

.unit-test:
  stage: test
  script:
    - echo "unit-test"

build-frontend:
  stage: build
  script:
    - echo "building frontend application"
    - npm run build
