stages:
  - install
  - test
  - build
  - package

default:
  image: node:20-buster-slim

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install react-scripts --save-dev


unit-test:
  stage: test
  before_script:
    - cd frontend
  script:
    - npm test

build-frontend:
  stage: build
  before_script:
    - cd frontend
  script:
    - echo "building frontend application"
    - npm run build
